prometheus:
  wal_directory: /var/lib/grafana/data/wal
  global:
    scrape_interval: 1m
    scrape_timeout: 10s
    evaluation_interval: 1m

  configs:
    - name: "backend"
      scrape_configs:
        - job_name: "backend"
          static_configs:
            - targets:
              - "localhost:4000"
      remote_write:
        - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
          basic_auth:
            username: 170329
            password: ${GRAFANA_PROMETHEUS_API_KEY}
